// <auto-generated />
using System;
using A_DAL.Context;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace A_DAL.Migrations
{
    [DbContext(typeof(QuanLyBanGiayDBContext))]
    [Migration("20221129144351_tiennam")]
    partial class tiennam
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "6.0.10")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder, 1L, 1);

            modelBuilder.Entity("A_DAL.Models.ChiTietSanPham", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("Anh")
                        .HasColumnType("varchar(50)")
                        .HasColumnName("Anh");

                    b.Property<decimal?>("GiaBan")
                        .HasColumnType("decimal")
                        .HasColumnName("GiaBan");

                    b.Property<decimal?>("GiaNhap")
                        .HasColumnType("decimal")
                        .HasColumnName("GiaNhap");

                    b.Property<Guid>("IDHSX")
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid>("IDMauSac")
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid>("IDSP")
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid>("IDSize")
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("MaSPCT")
                        .HasColumnType("nvarchar(20)")
                        .HasColumnName("MaSP");

                    b.Property<int>("SoLuong")
                        .HasColumnType("Int")
                        .HasColumnName("SoLuong");

                    b.Property<string>("TrangThai")
                        .HasColumnType("nvarchar(225)")
                        .HasColumnName("TrangThai");

                    b.HasKey("Id");

                    b.HasIndex("IDHSX");

                    b.HasIndex("IDMauSac");

                    b.HasIndex("IDSP");

                    b.HasIndex("IDSize");

                    b.ToTable("ChiTietSanPhams");
                });

            modelBuilder.Entity("A_DAL.Models.ChucVu", b =>
                {
                    b.Property<Guid>("ID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("MaCV")
                        .HasColumnType("varchar(20)")
                        .HasColumnName("MaCV");

                    b.Property<string>("TenCV")
                        .HasColumnType("nvarchar(20)")
                        .HasColumnName("TenCV");

                    b.HasKey("ID");

                    b.ToTable("chucVus");
                });

            modelBuilder.Entity("A_DAL.Models.GioHang", b =>
                {
                    b.Property<Guid>("ID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<decimal?>("DonGia")
                        .HasColumnType("decimal")
                        .HasColumnName("DonGia");

                    b.Property<Guid>("IDKH")
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid>("IDNV")
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("MaGH")
                        .HasColumnType("varchar(20)")
                        .HasColumnName("MaGH");

                    b.Property<int>("SoLuong")
                        .HasColumnType("Int")
                        .HasColumnName("SoLuong");

                    b.HasKey("ID");

                    b.HasIndex("IDKH");

                    b.HasIndex("IDNV");

                    b.ToTable("gioHangs");
                });

            modelBuilder.Entity("A_DAL.Models.GioHangCT", b =>
                {
                    b.Property<Guid>("IDSP")
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid>("IDGH")
                        .HasColumnType("uniqueidentifier");

                    b.Property<decimal?>("DonGia")
                        .HasColumnType("decimal")
                        .HasColumnName("DonGia");

                    b.Property<int>("SoLuong")
                        .HasColumnType("Int")
                        .HasColumnName("SoLuong");

                    b.HasKey("IDSP", "IDGH");

                    b.HasIndex("IDGH");

                    b.ToTable("gioHangCTs");
                });

            modelBuilder.Entity("A_DAL.Models.HangSanXuat", b =>
                {
                    b.Property<Guid>("ID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("MaHangSX")
                        .HasColumnType("varchar(20)")
                        .HasColumnName("MaHangSX");

                    b.Property<string>("TenHSX")
                        .HasColumnType("nvarchar(30)")
                        .HasColumnName("TenHangSX");

                    b.HasKey("ID");

                    b.ToTable("hangSanXuats");
                });

            modelBuilder.Entity("A_DAL.Models.HoaDon", b =>
                {
                    b.Property<Guid>("ID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<decimal?>("DonGia")
                        .HasColumnType("decimal")
                        .HasColumnName("DonGia");

                    b.Property<Guid>("IDKH")
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid>("IDNV")
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("MaHD")
                        .HasColumnType("varchar(30)")
                        .HasColumnName("MaHD");

                    b.Property<DateTime?>("NgayTao")
                        .HasColumnType("Datetime")
                        .HasColumnName("NgayTao");

                    b.Property<int>("SoLuong")
                        .HasColumnType("Int")
                        .HasColumnName("SoLuong");

                    b.Property<string>("TrangThai")
                        .HasColumnType("nvarchar(100)")
                        .HasColumnName("TrangThai");

                    b.HasKey("ID");

                    b.HasIndex("IDKH");

                    b.HasIndex("IDNV");

                    b.ToTable("hoaDons");
                });

            modelBuilder.Entity("A_DAL.Models.HoaDonCT", b =>
                {
                    b.Property<Guid>("IDSP")
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid>("IDHD")
                        .HasColumnType("uniqueidentifier");

                    b.Property<decimal?>("DonGia")
                        .HasColumnType("decimal")
                        .HasColumnName("DonGia");

                    b.Property<int?>("SoLuong")
                        .HasColumnType("Int")
                        .HasColumnName("SoLuong");

                    b.HasKey("IDSP", "IDHD");

                    b.HasIndex("IDHD");

                    b.ToTable("hoaDonCTs");
                });

            modelBuilder.Entity("A_DAL.Models.KhachHang", b =>
                {
                    b.Property<Guid>("ID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("DiaChi")
                        .HasColumnType("nvarchar(100)")
                        .HasColumnName("DiaChi");

                    b.Property<string>("MaKH")
                        .HasColumnType("varchar(20)")
                        .HasColumnName("MaKH");

                    b.Property<string>("SDT")
                        .HasColumnType("nvarchar(10)")
                        .HasColumnName("SDT");

                    b.Property<string>("Ten")
                        .HasColumnType("nvarchar(100)")
                        .HasColumnName("Ten");

                    b.HasKey("ID");

                    b.ToTable("khachHangs");
                });

            modelBuilder.Entity("A_DAL.Models.MauSac", b =>
                {
                    b.Property<Guid>("ID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("MaMau")
                        .HasColumnType("varchar(20)")
                        .HasColumnName("MaMau");

                    b.Property<string>("Mau")
                        .HasColumnType("nvarchar(20)")
                        .HasColumnName("Mau");

                    b.HasKey("ID");

                    b.ToTable("mausacs");
                });

            modelBuilder.Entity("A_DAL.Models.NhanVien", b =>
                {
                    b.Property<Guid>("ID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("DiaChi")
                        .HasColumnType("nvarchar(100)")
                        .HasColumnName("DiaChi");

                    b.Property<string>("Email")
                        .HasColumnType("varchar(50)")
                        .HasColumnName("Email");

                    b.Property<string>("GioiTinh")
                        .HasColumnType("varchar(10)")
                        .HasColumnName("GioiTinh");

                    b.Property<Guid>("IDCV")
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("MaNV")
                        .IsRequired()
                        .HasColumnType("varchar(20)")
                        .HasColumnName("MaNV");

                    b.Property<string>("MatKhau")
                        .HasColumnType("varchar(Max)")
                        .HasColumnName("MatKhau");

                    b.Property<DateTime?>("NgaySinh")
                        .HasColumnType("Datetime")
                        .HasColumnName("NgaySinh");

                    b.Property<string>("SDT")
                        .HasColumnType("varchar(30)")
                        .HasColumnName("SDT");

                    b.Property<string>("Ten")
                        .HasColumnType("nvarchar(100)")
                        .HasColumnName("Ten");

                    b.Property<string>("TrangThai")
                        .HasColumnType("nvarchar(100)")
                        .HasColumnName("TrangThai");

                    b.HasKey("ID");

                    b.HasIndex("IDCV");

                    b.ToTable("nhanViens");
                });

            modelBuilder.Entity("A_DAL.Models.SanPham", b =>
                {
                    b.Property<Guid>("ID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("MaSP")
                        .HasColumnType("varchar(20)")
                        .HasColumnName("MaSP");

                    b.Property<string>("TenSP")
                        .HasColumnType("varchar(100)")
                        .HasColumnName("TenSP");

                    b.HasKey("ID");

                    b.ToTable("sanPhams");
                });

            modelBuilder.Entity("A_DAL.Models.Size", b =>
                {
                    b.Property<Guid>("ID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("MaSize")
                        .HasColumnType("varchar(20)")
                        .HasColumnName("MaSize");

                    b.Property<int?>("SoSize")
                        .HasColumnType("Int")
                        .HasColumnName("Size");

                    b.HasKey("ID");

                    b.ToTable("sizes");
                });

            modelBuilder.Entity("A_DAL.Models.ChiTietSanPham", b =>
                {
                    b.HasOne("A_DAL.Models.HangSanXuat", "HangSanXuat")
                        .WithMany()
                        .HasForeignKey("IDHSX")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("A_DAL.Models.MauSac", "mausac")
                        .WithMany()
                        .HasForeignKey("IDMauSac")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("A_DAL.Models.SanPham", "SanPham")
                        .WithMany()
                        .HasForeignKey("IDSP")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("A_DAL.Models.Size", "size")
                        .WithMany()
                        .HasForeignKey("IDSize")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("HangSanXuat");

                    b.Navigation("SanPham");

                    b.Navigation("mausac");

                    b.Navigation("size");
                });

            modelBuilder.Entity("A_DAL.Models.GioHang", b =>
                {
                    b.HasOne("A_DAL.Models.KhachHang", "KhachHang")
                        .WithMany()
                        .HasForeignKey("IDKH")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("A_DAL.Models.NhanVien", "NhanVien")
                        .WithMany()
                        .HasForeignKey("IDNV")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("KhachHang");

                    b.Navigation("NhanVien");
                });

            modelBuilder.Entity("A_DAL.Models.GioHangCT", b =>
                {
                    b.HasOne("A_DAL.Models.GioHang", "GioHang")
                        .WithMany()
                        .HasForeignKey("IDGH")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("A_DAL.Models.ChiTietSanPham", "ChiTietSanPham")
                        .WithMany()
                        .HasForeignKey("IDSP")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("ChiTietSanPham");

                    b.Navigation("GioHang");
                });

            modelBuilder.Entity("A_DAL.Models.HoaDon", b =>
                {
                    b.HasOne("A_DAL.Models.KhachHang", "KhachHang")
                        .WithMany()
                        .HasForeignKey("IDKH")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("A_DAL.Models.NhanVien", "NhanVien")
                        .WithMany()
                        .HasForeignKey("IDNV")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("KhachHang");

                    b.Navigation("NhanVien");
                });

            modelBuilder.Entity("A_DAL.Models.HoaDonCT", b =>
                {
                    b.HasOne("A_DAL.Models.HoaDon", "HoaDon")
                        .WithMany()
                        .HasForeignKey("IDHD")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("A_DAL.Models.ChiTietSanPham", "ChiTietSanPham")
                        .WithMany()
                        .HasForeignKey("IDSP")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("ChiTietSanPham");

                    b.Navigation("HoaDon");
                });

            modelBuilder.Entity("A_DAL.Models.NhanVien", b =>
                {
                    b.HasOne("A_DAL.Models.ChucVu", "ChucVu")
                        .WithMany()
                        .HasForeignKey("IDCV")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("ChucVu");
                });
#pragma warning restore 612, 618
        }
    }
}
